# Generated by Django 4.0.10 on 2024-02-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='link_2gis',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='schedule',
        ),
        migrations.AddField(
            model_name='branch',
            name='schedule',
            field=models.ManyToManyField(related_name='branch_schedule', to='users.schedule'),
        ),
    ]
