# Generated by Django 4.0.10 on 2024-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_branch_link_2gis_remove_branch_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
