# Generated by Django 4.0.10 on 2024-02-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_login_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='table_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
