# Generated by Django 4.0.10 on 2024-02-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
