# Generated by Django 4.2 on 2024-02-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_staff_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='branches_schedule', related_query_name='branch_schedule', to='users.schedule'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('bartender', 'Bartender')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='working_days',
            field=models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=15),
        ),
        migrations.CreateModel(
            name='BranchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='employees_schedule', related_query_name='employee_schedule', to='users.schedule'),
        ),
    ]
