# Generated by Django 4.2 on 2024-02-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_schedule_working_days_schedule_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_wednesday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='working_days',
            field=models.TextField(default='[false, false, false, false, false, false, false]', verbose_name='Working Days'),
        ),
    ]
