# Generated by Django 4.2 on 2024-02-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_schedule_day_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='working_days',
            field=models.JSONField(default=dict, verbose_name='Working Days'),
        ),
    ]
