# Generated by Django 4.2 on 2024-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_employeeschedule_alter_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='employee_schedule', related_query_name='employee_schedule', to='users.employeeschedule'),
        ),
    ]
