# Generated by Django 4.2 on 2024-02-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_is_staff_alter_customuser_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='schedule',
            new_name='employee_schedule',
        ),
    ]
