# Generated by Django 4.2 on 2024-02-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_schedule_customuser_employee_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employee_schedule',
            new_name='schedule',
        ),
    ]
