# Generated by Django 4.2 on 2024-02-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_employee_schedule_customuser_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='schedule',
            new_name='schedules',
        ),
    ]
