# Generated by Django 4.2 on 2024-02-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_schedule_customuser_schedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='schedules',
            new_name='schedule',
        ),
    ]
