# Generated by Django 4.2 on 2024-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_customer_email_remove_order_item_and_more'),
        ('users', '0026_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.order'),
        ),
    ]
