# Generated by Django 4.2 on 2024-02-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_employeeprofile_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='name',
            new_name='first_name',
        ),
    ]
