# Generated by Django 4.2 on 2024-02-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_customerprofile_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
