# Generated by Django 4.2 on 2024-02-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_employeeschedule_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartenderprofile',
            name='employee_schedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeschedule'),
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='employee_schedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeschedule'),
        ),
    ]
