# Generated by Django 4.2 on 2024-02-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_bartenderprofile_employee_schedules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiterprofile',
            old_name='employee_schedules',
            new_name='schedule',
        ),
    ]
