# Generated by Django 4.2 on 2024-02-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_employee_schedules_waiterprofile_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartenderprofile',
            old_name='employee_schedules',
            new_name='schedule',
        ),
    ]
