# Generated by Django 4.2 on 2024-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_employee_schedules_bartenderprofile_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='day',
            field=models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], max_length=10),
        ),
    ]
