# Generated by Django 4.2 on 2024-02-25 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_employeeschedule_day_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterprofile',
            name='waiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
