# Generated by Django 4.2 on 2024-02-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_waiterprofile_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterprofile',
            name='waiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
