# Generated by Django 4.2 on 2024-02-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_waiterprofile_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterprofile',
            name='waiter_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeprofile'),
        ),
    ]
