# Generated by Django 4.2 on 2024-02-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_waiterprofile_waiter_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiterprofile',
            name='waiter_profile',
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='waiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiterprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
