# Generated by Django 4.2 on 2024-02-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_waiterprofile_waiter_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartenderprofile',
            old_name='bartender',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='waiterprofile',
            old_name='waiter',
            new_name='employee',
        ),
    ]
