# Generated by Django 4.2 on 2024-02-26 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_rename_bartender_bartenderprofile_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
