# Generated by Django 4.2 on 2024-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_waiterprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='user_type',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
