# Generated by Django 4.2 on 2024-02-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_employeeprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='user_type',
            field=models.CharField(max_length=50),
        ),
    ]
