# Generated by Django 4.2 on 2024-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_employeeprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='user_type',
            field=models.CharField(default='Waiter', max_length=50),
        ),
    ]
