# Generated by Django 4.2 on 2024-02-27 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_employeeprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartenderprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bartenderprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiterprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
