# Generated by Django 4.2 on 2024-02-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_bartenderprofile_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartenderprofile',
            old_name='employee',
            new_name='employee_profile',
        ),
        migrations.RenameField(
            model_name='waiterprofile',
            old_name='employee',
            new_name='employee_profile',
        ),
    ]
