# Generated by Django 4.2 on 2024-02-27 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_employee'),
        ('users', '0055_profile_remove_employeeprofile_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeschedule'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
