# Generated by Django 4.2 on 2024-02-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_delete_employeeprofile_profile_schedule_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartenderprofile',
            old_name='employee',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='waiterprofile',
            old_name='employee',
            new_name='user',
        ),
    ]
