# Generated by Django 4.2 on 2024-02-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_rename_employee_bartenderprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='employee',
            new_name='user',
        ),
    ]
