# Generated by Django 4.2 on 2024-02-27 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_rename_employee_employeeschedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
