# Generated by Django 4.2 on 2024-02-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_employeeschedule_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='user',
            new_name='employee',
        ),
    ]
