# Generated by Django 4.2 on 2024-02-28 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_rename_user_employeeschedule_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='orders',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='bonus_points',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customerprofile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bonus_points',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Waiter', 'Waiter'), ('Bartender', 'Bartender'), ('Customer', 'Customer')], default='Waiter', max_length=50),
        ),
    ]
