# Generated by Django 4.2 on 2024-02-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_rename_user_employeeschedule_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer',
            new_name='user',
        ),
    ]
