# Generated by Django 4.2 on 2024-02-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_rename_order_customerprofile_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='bonus',
            new_name='bonus_points',
        ),
    ]
