# Generated by Django 4.2 on 2024-02-28 21:01

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_rename_bonus_customerprofile_bonus_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.PositiveIntegerField(default=100)),
                # Add other fields here...
                ('customer', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(
                    blank=True, max_length=50, null=True)),
            ],
        ),
    ]
