# Generated by Django 4.2 on 2024-03-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_customer'),
        ('users', '0064_rename_bonus_customerprofile_bonus_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
