# Generated by Django 4.2 on 2024-02-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_rename_bonus_customerprofile_bonus_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='bonus_points',
            new_name='bonus',
        ),
    ]
