# Generated by Django 4.2 on 2024-03-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_alter_customerprofile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='orders',
        ),
    ]
