# Generated by Django 4.2 on 2024-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_customerprofile_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
