# Generated by Django 4.2 on 2024-03-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_branch_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branch_images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.branch')),
            ],
        ),
    ]
