# Generated by Django 4.2 on 2024-03-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_branch_image_delete_branchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterprofile',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='users.branch'),
            preserve_default=False,
        ),
    ]
