# Generated by Django 4.2 on 2024-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_bartenderprofile_branch_alter_profile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartenderprofile',
            name='user_type',
            field=models.CharField(default='Bartender', max_length=50),
        ),
        migrations.AddField(
            model_name='waiterprofile',
            name='user_type',
            field=models.CharField(default='Waiter', max_length=50),
        ),
    ]
