# Generated by Django 4.2 on 2024-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_bartenderprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='user_type',
            field=models.CharField(default='Customer', max_length=50),
        ),
    ]
