# Generated by Django 4.2 on 2024-03-25 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_bartenderprofile_branch_bartenderprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartenderprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartender_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
