# Generated by Django 4.2 on 2024-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_bartenderprofile_user_alter_waiterprofile_user'),
    ]

    operations = [
    ]
