# Generated by Django 4.2 on 2024-03-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_order_branch_customerorder'),
        ('users', '0077_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerorder'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='customers', to='orders.customerorder'),
        ),
    ]
