# Generated by Django 4.2 on 2024-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_bartenderprofile_email_waiterprofile_email'),
    ]

    operations = [
    ]
