# Generated by Django 4.2 on 2024-03-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_customerorder_branch_and_more'),
        ('users', '0079_alter_customerprofile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='orders',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Waiter', 'Waiter'), ('Bartender', 'Bartender')], default='Waiter', max_length=50),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='orders',
            field=models.ManyToManyField(related_name='customer_profiles', to='orders.order'),
        ),
    ]
