# Generated by Django 4.2 on 2024-03-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_delete_customerorder'),
        ('users', '0080_remove_customerprofile_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartenderprofile',
            name='user_type',
            field=models.CharField(default='Bartender', max_length=50),
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='orders',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Waiter', 'Waiter'), ('Bartender', 'Bartender'), ('Customer', 'Customer')], default='Waiter', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='Waiter', max_length=50),
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='user_type',
            field=models.CharField(default='Waiter', max_length=50),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
