# Generated by Django 4.2.11 on 2024-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_alter_bartenderprofile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Waiter', 'Waiter'), ('Bartender', 'Bartender'), ('Customer', 'Customer'), ('Admin', 'Admin')], default='Waiter', max_length=50),
        ),
    ]
