# Generated by Django 4.2.11 on 2024-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartenderprofile',
            name='user_type',
            field=models.CharField(default='Бармен', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user_type',
            field=models.CharField(default='Посетитель', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Официант', 'Официант'), ('Бармен', 'Бармен'), ('Посетитель', 'Посетитель'), ('Администратор', 'Администратор')], default='Официант', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='Официант', max_length=50),
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='user_type',
            field=models.CharField(default='Официант', max_length=50),
        ),
    ]
