version: "3.12"

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8000:8000"
    command: >
      bash -c "/wait-for-it.sh -t 30 db:5432 -- python manage.py collectstatic --no-input && python manage.py migrate && gunicorn neocafe_config.wsgi:application -w 4 -b 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_custom_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  channels:
    build: .
    volumes:
      - .:/config
    ports:
      - "8001:8001"
    command: >
      bash -c "uvicorn neocafe_config.asgi:application --host 0.0.0.0 --port 8001 --reload"
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - my_custom_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my_custom_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
