version: "3.12"

services:
  db:
    image: postgres:latest
    networks:
      - my_custom_network
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      aliases:
        - db

  app:
    build: .
    networks:
      - my_custom_network
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8000:8000"
    command: >
      bash -c "/wait-for-it.sh -t 
