version: "3.12"

services:
  db:
    image: postgres:latest
    networks:
      my_custom_network:
        aliases:
          - db
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/config
    ports:
      - "8000:8000"
    command: >
      bash -c "uvicorn neocafe_config.asgi:application --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - my_custom_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
