# Generated by Django 4.2.11 on 2024-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Готов', 'Готов'), ('Ожидание', 'Ожидание')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
