# Generated by Django 4.2.11 on 2024-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='table_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
