# Generated by Django 4.2.11 on 2024-04-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_order_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Готово', 'Готово'), ('Ожидание', 'Ожидание')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
