# Generated by Django 4.2.11 on 2024-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
