# Generated by Django 4.2.11 on 2024-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_remove_notification_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='table',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
