# Generated by Django 4.2.11 on 2024-04-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='table',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
