# Generated by Django 4.2.11 on 2024-04-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
    ]
