# Generated by Django 4.2.11 on 2024-04-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_notification_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='position',
        ),
    ]
