# Generated by Django 4.2.11 on 2024-04-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_notification_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='table',
        ),
    ]
