# Generated by Django 4.2.11 on 2024-04-17 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0044_rename_orderitemextraproduct_extraitemtoorder_and_more'),
        ('notification', '0013_remove_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
