# Generated by Django 4.2 on 2024-02-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='item_name',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Выпечка', max_length=255),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='name',
            field=models.CharField(default='Выпечка', max_length=255),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category'),
        ),
    ]
