# Generated by Django 4.2 on 2024-02-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(default='Выпечка', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category'),
        ),
    ]
