# Generated by Django 4.2 on 2024-02-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='image',
            new_name='item_image',
        ),
    ]
