# Generated by Django 4.2 on 2024-02-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_customuser_schedule'),
        ('menu', '0004_rename_image_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='type',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Выпечка', max_length=255)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('current_quantity', models.PositiveIntegerField(default=100)),
                ('measurement_unit', models.CharField(choices=[('гр', 'Грамм'), ('кг', 'Килограмм'), ('мл', 'мл'), ('литр', 'Литр'), ('шт', 'Штук')], max_length=15)),
                ('type', models.CharField(choices=[('готовое', 'Готовое изделие'), ('сырье', 'Сырье')], max_length=15)),
                ('minimum_limit', models.PositiveIntegerField(default=10)),
                ('restock_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='users.branch')),
            ],
        ),
    ]
