# Generated by Django 4.2 on 2024-02-13 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_customuser_schedule'),
        ('menu', '0005_remove_category_category_image_remove_menu_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='current_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='minimum_limit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='restock_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Выпечка', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_quantity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('restock_date', models.DateTimeField(auto_now_add=True)),
                ('is_enough', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu_item')),
            ],
        ),
    ]
