# Generated by Django 4.2 on 2024-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_item_current_quantity_menu_item_minimum_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='minimum_quantity',
            new_name='minimum_limit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='stock',
            name='measurement_unit',
            field=models.CharField(choices=[('гр.', 'гр.'), ('кг.', 'кг.'), ('мл.', 'мл.'), ('л.', 'л.'), ('шт.', 'шт.')], default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_item',
            field=models.CharField(default=110, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Готовое', 'Готовое изделие'), ('Из сырья', 'Из сырья')], default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='restock_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
