# Generated by Django 4.2 on 2024-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_minimum_quantity_stock_minimum_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='restock_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
