# Generated by Django 4.2 on 2024-02-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customuser_user_type'),
        ('menu', '0008_alter_stock_restock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='branch',
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.branchstock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.branchstock'),
        ),
    ]
