# Generated by Django 4.2 on 2024-02-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_stock_stock_stock_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='current_quantity',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='minimum_limit',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='restock_date',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='branch_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.stock'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='stock',
            name='measurement_unit',
            field=models.CharField(choices=[('гр', 'гр'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л'), ('шт', 'шт')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Готовое', 'Готовое изделие'), ('Cырье', 'Cырье')], max_length=15),
        ),
    ]
