# Generated by Django 4.2 on 2024-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_menu_item_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='branch',
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Готовое', 'Готовое изделие'), ('Сырье', 'Сырье')], max_length=15),
        ),
    ]
