# Generated by Django 4.2 on 2024-02-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customuser_user_type'),
        ('menu', '0015_remove_menu_item_branch_alter_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='users.branch'),
            preserve_default=False,
        ),
    ]
