# Generated by Django 4.2 on 2024-02-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_menu_item_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='branch',
        ),
    ]
