# Generated by Django 4.2 on 2024-02-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_stock_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='menu_item',
        ),
    ]
