# Generated by Django 4.2 on 2024-02-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_ingredient_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_enough',
        ),
    ]
