# Generated by Django 4.2 on 2024-02-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_remove_stock_is_enough'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
    ]
