# Generated by Django 4.2 on 2024-02-18 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_remove_ingredient_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.DeleteModel(
            name='MenuItemIngredient',
        ),
    ]
