# Generated by Django 4.2 on 2024-02-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_alter_menu_item_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Готовое', 'Готовое изделие'), ('Сырье', 'Сырье')], max_length=15),
        ),
    ]
