# Generated by Django 4.2 on 2024-03-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
