# Generated by Django 4.2.11 on 2024-04-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_delete_extraitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_extra_product', models.CharField(choices=[('Молоко', 'Молоко'), ('Сироп', 'Сиропы')], max_length=20, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('choice_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_products', to='menu.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
