# Generated by Django 4.2 on 2024-02-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_customuser_schedule'),
        ('menu', '0007_rename_minimum_quantity_stock_minimum_limit_and_more'),
        ('orders', '0002_alter_order_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal_price', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='menu.menu_item')),
            ],
        ),
    ]
