# Generated by Django 4.2 on 2024-02-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtotal_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
