# Generated by Django 4.2 on 2024-02-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_remove_ingredient_stock_menu_item_branch_and_more'),
        ('users', '0026_alter_customuser_user_type'),
        ('orders', '0004_remove_cart_quantity_remove_cart_subtotal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='menu.menu_item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='new', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
