# Generated by Django 4.2 on 2024-02-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_customerprofile_bonus_and_more'),
        ('menu', '0027_alter_stock_type'),
        ('orders', '0008_remove_employeeprofile_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu_item')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_orders', to='users.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('In Venue', 'In Venue'), ('Takeaway', 'Takeaway')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Cancelled', 'Cancelled'), ('Done', 'Done')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
        migrations.AddField(
            model_name='itemtoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ITO', to='orders.order'),
        ),
    ]
