# Generated by Django 4.2 on 2024-02-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_itemtoorder_remove_order_items_alter_order_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='branch',
        ),
    ]
