# Generated by Django 4.2 on 2024-02-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_profile_remove_employeeprofile_employee_and_more'),
        ('orders', '0010_remove_table_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_orders', to='users.profile'),
        ),
    ]
