# Generated by Django 4.2 on 2024-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], default='Reserved', max_length=20),
        ),
    ]
