# Generated by Django 4.2 on 2024-03-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_rename_bonus_customerprofile_bonus_points'),
        ('orders', '0018_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
    ]
