# Generated by Django 4.2 on 2024-03-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_table_is_available_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
