# Generated by Django 4.2 on 2024-03-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_table_status_table_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
