# Generated by Django 4.2 on 2024-03-17 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_branch_image_delete_branchimage'),
        ('orders', '0025_rename_status_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branch'),
        ),
    ]
