# Generated by Django 4.2 on 2024-03-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_branch_image_delete_branchimage'),
        ('orders', '0026_table_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
    ]
