# Generated by Django 4.2 on 2024-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_table_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'), ('Готов', 'Готов'), ('Отменен', 'Отменен'), ('Завершен', 'Завершен')], default='Новый', max_length=20),
        ),
    ]
