# Generated by Django 4.2 on 2024-03-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
