# Generated by Django 4.2 on 2024-03-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_remove_bartenderprofile_branch_and_more'),
        ('orders', '0032_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.profile'),
        ),
    ]
