# Generated by Django 4.2 on 2024-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_points_to_subtract',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
