# Generated by Django 4.2 on 2024-03-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_order_branch_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ito_items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.itemtoorder'),
        ),
        migrations.AlterField(
            model_name='itemtoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ito_entries', to='orders.order'),
        ),
    ]
