# Generated by Django 4.2 on 2024-03-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_alter_customerprofile_orders'),
        ('orders', '0038_order_ito_items_alter_itemtoorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ito_items',
        ),
        migrations.AlterField(
            model_name='itemtoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ITO', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.branch'),
        ),
    ]
