# Generated by Django 4.2 on 2024-03-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_remove_customerprofile_orders_and_more'),
        ('orders', '0039_remove_customerorder_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
