# Generated by Django 4.2.11 on 2024-04-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_itemtoorder_extra_product_orderitemextraproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtoorder',
            name='extra_product',
        ),
        migrations.DeleteModel(
            name='OrderItemExtraProduct',
        ),
    ]
