# Generated by Django 4.2.11 on 2024-04-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_extraitem'),
        ('orders', '0042_remove_itemtoorder_extra_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtoorder',
            name='extra_product',
            field=models.ManyToManyField(blank=True, related_name='extra_order', to='menu.extraitem'),
        ),
        migrations.CreateModel(
            name='OrderItemExtraProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('extra_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.extraitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.itemtoorder')),
            ],
        ),
    ]
