# Generated by Django 4.2.11 on 2024-04-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_extraitem'),
        ('orders', '0043_itemtoorder_extra_product_orderitemextraproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemExtraProduct',
            new_name='ExtraItemToOrder',
        ),
        migrations.RenameField(
            model_name='extraitemtoorder',
            old_name='extra_product',
            new_name='extra_item',
        ),
        migrations.AlterUniqueTogether(
            name='extraitemtoorder',
            unique_together={('order_item', 'extra_item')},
        ),
    ]
