# Generated by Django 4.2.11 on 2024-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_rename_orderitemextraproduct_extraitemtoorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('В заведении', 'В заведении'), ('На вынос', 'На вынос')], max_length=20),
        ),
    ]
