# Generated by Django 4.2.11 on 2024-04-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_remove_extraitem_choice_category_and_more'),
        ('orders', '0045_alter_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtoorder',
            name='extra_product',
        ),
        migrations.AddField(
            model_name='itemtoorder',
            name='extra_temp',
            field=models.ManyToManyField(blank=True, related_name='extra_order_temp', to='menu.extraitem'),
        ),
    ]
