# Generated by Django 4.2.11 on 2024-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_remove_extraitem_choice_category_and_more'),
        ('orders', '0046_remove_itemtoorder_extra_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtoorder',
            name='extra_temp',
        ),
        migrations.AddField(
            model_name='itemtoorder',
            name='extra_product',
            field=models.ManyToManyField(blank=True, related_name='extra_order', through='orders.ExtraItemToOrder', to='menu.extraitem'),
        ),
    ]
